[package]
name = "chameleon"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "magics"
path = "src/bin/magics.rs"
[[bin]]
name = "perft"
path = "src/bin/perft.rs"

[dependencies]
arrayvec = "0.7.4"
rand = { version = "0.8.5", features = ["small_rng"] }
clap = { version = "4.4.18", features = ["derive"] }

[profile.release]
lto = true
panic = "abort"
codegen-units = 1
incremental = true

[profile.dev]
opt-level = 2
incremental = true
